services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - .next:/usr/src/app/.next

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  .next:
  db_data:

