# services:
#   web:
#     build:
#       context: .
#     environment:
#       NODE_ENV: development
#     ports:
#       - 3000:3000
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#       - /usr/src/app/.next
#     command: npm run dev

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: foocre_development
#     ports:
#       - 3306:3306
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./init:/docker-entrypoint-initdb.d

# volumes:
#   .next:
#   db_data:

version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
      - type: volume
        target: /usr/src/app/.next

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foocre_development
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
