import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import CssBaseline from '@mui/material/CssBaseline';

import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

import styles from '@/styles/ContentBox.module.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <AppRouterCacheProvider>
          <CssBaseline />
          <Header />
          <div className={styles.ContentBox}>
            {children}
          </div>
          <Footer />
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
